import { ShortenUrlForm } from "@/features/shortenUrl/components/ShortenUrlForm";

export default function AppPage() {
  return (
    <main className="min-h-screen bg-[linear-gradient(180deg,#f8fafc_0%,#eef2ff_45%,#ffffff_100%)] px-6 py-16 text-slate-950">
      <section className="mx-auto flex w-full max-w-5xl flex-col gap-10">
        <div className="max-w-2xl space-y-4">
          <p className="text-sm font-semibold tracking-[0.22em] text-sky-700 uppercase">
            Shorten URL
          </p>
          <h1 className="text-4xl font-semibold tracking-tight sm:text-5xl">
            Turn a long link into something compact.
          </h1>
          <p className="text-base leading-7 text-slate-600 sm:text-lg">
            Paste a full URL, submit the form, and get a short link generated by
            the backend feature.
          </p>
        </div>

        <ShortenUrlForm />
      </section>
    </main>
  );
}
